### ISSUE TITLE
Potential issue with 'filling horizontal gaps on slopes' option

### ISSUE THREAD

**Issue by espwarrior** [supermerill/Slic3r#112] opened 2019-10-30 22:46 UTC
### Version
2.1.44

### Operating system type + version
Windows 10 Professional

### 3D printer brand / version + firmware version
N/A

### Behavior
Enabling the option 'filling horizontal gaps on slopes' generates circular perimeters on layer 3 (@0.60mm) to cover open spaces in my model (inset text facing the build plate), instead of generating the expected solid and bridge infill. The criteria for a slope don't seem to be present, but I could be misinterpreting what this option is intended to achieve. I think the option was enabled due to imported settings from a previous version of Slic3r++ 1.42.2.

With the 'extra perimeters' option enabled:

![Tube Cap Circular Infill Issue](https://user-images.githubusercontent.com/16756313/67904074-9fa66500-fb6d-11e9-876f-92e06aab6a18.png)

![Tube Cap Circular Infill Issue Cause](https://user-images.githubusercontent.com/16756313/67904083-a59c4600-fb6d-11e9-95c0-d697bb2a9fb2.png)

With the 'extra perimeters' option disabled (which is the expected result):

![Tube Cap Desired Infill](https://user-images.githubusercontent.com/16756313/67904179-eb590e80-fb6d-11e9-8b97-a1ccf95e6231.png)

### Project File (.3MF) where problem occurs

[Tube Cap.zip](https://github.com/supermerill/Slic3r/files/3791369/Tube.Cap.zip)

### Brim artifacts

Please also note that while 'Interior brim width' is zero, there are circular fragments of brim within the perimeters of some letters in the first layer. This might be a separate issue however.

![Tube Cap Circular Brim Issue](https://user-images.githubusercontent.com/16756313/67904804-c36aaa80-fb6f-11e9-8d43-70a6b2a745c8.png)

**Edit**: added a screenshot of the brim artifacts.

**Comment by supermerill** [comment] 2019-10-30 23:40
I think the first is a duplicate of #46. It's not really a bug but an inconvenience: as long as there are a detected hole, it add a perimeter. As your text / hole go to the middle, it adds perimeter to the middle. The algorithm should be changed/ modified.

The second problem is a more serous bug, can you paste here your project file (.3mf in a zip) ?

**Comment by espwarrior** [comment] 2019-10-31 08:46
Ah, yes, #46 looks like the same issue indeed. It was problematic because the holes were covered by regular perimeters instead of using bridges, causing a bit of sagging. Apologies, I had included the [link](https://github.com/supermerill/Slic3r/files/3791369/Tube.Cap.zip) to the 3mf already, but not in a logical and clearly visible spot.

**Comment by supermerill** [comment] 2019-11-01 21:36
I understand now why it creates a bit of brim inside: it's because i changed the logic to allow islands inside holes, and here you have the D inside the P that trigger the brim.

I'll add an other setting to enable/disable brim inside holes.

**Comment by espwarrior** [comment] 2019-11-01 23:03
Cool! At first, to me it seemed like one big oversized brim in the wrong place, but now I notice that there are indeed actually five separate 4mm brims for the islands within a, e, p, o which have overlap. I'm glad you found the cause!

**Closed** 2019-11-06 14:12 UTC
Labels: bug, fixed for the next version
