### ISSUE TITLE
[Feature Request] Non Planar Slicing

### ISSUE THREAD

**Issue by abdbeg** [supermerill/Slic3r#158] opened 2020-02-04 05:58 UTC
Hi

Thanks for all your work,  it would be very nice if you can implement this: https://github.com/Zip-o-mat/Slic3r/tree/nonplanar , nonplanar option for the slicer, that guy already made it for old Slic3r version, it would be nice if you can add it to your, thanks.

**Comment by supermerill** [comment] 2020-02-04 09:48
duplicate of #84
Please comment the other issue.

The creator said it's not ready for integration and he wants to modify it before. So for the moment, I wait.

**Closed by supermerill** 2020-02-04 09:48 UTC

**Comment by abdbeg** [comment] 2020-02-04 09:49
Sorry, i didn't find it, thanks!
