### ISSUE TITLE
[Request] Seam location modifier

### ISSUE THREAD

**Issue by SigmaRelief** [supermerill/Slic3r#220] opened 2020-05-02 02:24 UTC
New feature request to add modifier types to block seams or force seams inside their volume.  This would work in conjunction with the current seam logic, but would simply narrow the scope of where the seam can be placed.

This would allow seams to be manually excluded from high aesthetic areas or forced into low value areas without relying on a one-size-fits-all formula.  There would obviously need to be fallback logic to handle cases with multiple modifiers, perimeters where mo modifiers cross, etc. but the heiarchy may not be too complicated.

**Comment by supermerill** [comment] 2020-05-02 17:33
seems like the duplicate of #152, please use the other issue.

**Closed** 2020-05-02 17:33 UTC
Labels: duplicate
